/**
 * AI Image Generation
 */

const APIs = require('../../utils/api');
const config = require('/root/pyBot/config');
const axios = require('axios');

const processedMessages = new Set();

module.exports = {
  name: 'imagine',
  aliases: ['aiimg', 'genimg', 'draw'],
  category: 'ai',
  description: 'Generate AI images from text',
  usage: '.imagine <prompt>',
  
  async execute(sock, msg, args, extra) {
    try {
      if (processedMessages.has(msg.key.id)) return;
      processedMessages.add(msg.key.id);
      setTimeout(() => processedMessages.delete(msg.key.id), 5 * 60 * 1000);

      if (args.length === 0) {
        return extra.reply('❌ Usage: .imagine <prompt>\n\nExample: .imagine A cat sitting on a rainbow');
      }

      const prompt = args.join(' ');
      await sock.sendMessage(msg.key.remoteJid, { react: { text: '🎨', key: msg.key } });
      await extra.reply('⏳ Generating AI image...');

      try {
        const response = await axios.get(`https://api.siputzx.my.id/api/ai/text2img`, {
          params: { prompt }
        });

        const data = response.data;
        if (data.status && data.data && data.data.image) {
          await sock.sendMessage(msg.key.remoteJid, {
            image: { url: data.data.image },
            caption: `*AI Generated by ${config.botName.toUpperCase()}*\n\n📝 ${prompt}`
          }, { quoted: msg });
        } else {
          await extra.reply('❌ Failed to generate image!');
        }
      } catch (err) {
        await extra.reply('❌ Error generating image!');
      }
    } catch (error) {
      console.error('Imagine error:', error);
      await extra.reply('❌ An error occurred!');
    }
  }
};